name: AI Digest Updater

on:
  schedule:
    # 9 AM IST = 3:30 AM UTC, 3 PM IST = 9:30 AM UTC
    - cron: '30 3 * * *'
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  update-ai-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AI Digest script
        run: python your_script.py
        # replace `your_script.py` with your actual script name

      - name: Commit and push changes (force overwrite)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin main
          git checkout main
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping push."
          else
            git commit -m "Update AI Digest"
            git push origin main --force
          fi
