name: Build AI Digest

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC (~5:30 AM IST)
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run digest builder
        run: node scripts/build-digest.mjs

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/api/ai-digest.json
          git commit -m "Update AI Digest"
          git push
